### PR TITLE
type checking + use `.slice(-1)`

### PR DESCRIPTION
**Pull request by ruffle1986**
https://github.com/IonicaBizau/last-char/issues/1

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Thanks for your contributions, @ruffle1986!

`slice` is slower than `chartAt`, so that's why I used `charAt`

**Comment by IonicaBizau** [comment]
Actually, checking the string is a good thing. Just, please, use `charAt` instead of `slice`. :smile:

**Comment by ruffle1986** [comment]
Oh, really. Thanks for pointing out. :+1: 

http://jsperf.com/last-char

**Comment by IonicaBizau** [comment]
@ruffle1986 Cool! :+1: Please add yourself as contributor. :smile:

**Comment by ruffle1986** [comment]
Just for the record. it's not significant but in firefox 41.0.2 charAt the slowest. :D

**Comment by IonicaBizau** [comment]
@ruffle1986 Haha, would be curious how is the performance difference in Node.js. :grin:

**Comment by IonicaBizau** [comment]
:ship: **`1.1.0`** :tada: Thanks! :sparkles:

**Pull request merged**
